### ISSUE TITLE
[Feature Request] 能否新增HarmonyOS Sans系列字体支持

### ISSUE THREAD

**Issue by 8MiYile** [YutaYamamoto212/ModernFontPack#1]
### 请求说明

想要字体支持列表内有HarmonyOS Sans字体这个分支 感谢

**Comment by YutaYamamoto212** [comment]
感谢您的建议，但我认为HarmonyOS Sans字体与我的字体包现在使用的Noto Sans CJK（思源黑体）字体太相似了。因此，我不会将它包含在我的项目中。如果你想用这个字体开发你想要的字体包，可以参考我的字体包的设计方法来设计。您也可以加入我的[Discord 服务器](https://discord.gg/tqzdEaBAcn)进行进一步的技术咨询。
